export const AUDIT_ACTIONS = {
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",

    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",

    CREATE_OFFER: "CREATE_OFFER",
    ACCEPT_OFFER: "ACCEPT_OFFER",
    REJECT_OFFER: "REJECT_OFFER",

    CREATE_ORDER: "CREATE_ORDER",
    CANCEL_ORDER: "CANCEL_ORDER",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED",

    UPDATE_PROFILE: "UPDATE_PROFILE",
} as const;

export const AUDIT_ENTITY_TYPES = {
    CUSTOMER: "CUSTOMER",
    PRODUCT: "PRODUCT",
    OFFER: "OFFER",
    ORDER: "ORDER",
    PAYMENT: "PAYMENT",
    REVIEW: "REVIEW",
    PROFILE: "PROFILE",
} as const;